/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
import Modelo.ModelCliente;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JSpinner;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Danie
 */
public class vista_factura extends javax.swing.JFrame {

    /**
     * Creates new form vista_factura
     */
    public vista_factura() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        DlgCliente = new javax.swing.JDialog();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabladlg = new javax.swing.JTable();
        jToolBar2 = new javax.swing.JToolBar();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        jLabel17 = new javax.swing.JLabel();
        txtbuscardlg = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        btnseleccionardlg = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        jPanel5 = new javax.swing.JPanel();
        lbltitulo1 = new javax.swing.JLabel();
        DlgProducto = new javax.swing.JDialog();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabladlgProd = new javax.swing.JTable();
        jToolBar3 = new javax.swing.JToolBar();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        jLabel18 = new javax.swing.JLabel();
        txtbuscardlg1 = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JToolBar.Separator();
        btnseleccionardlgProd = new javax.swing.JButton();
        jSeparator9 = new javax.swing.JToolBar.Separator();
        jPanel6 = new javax.swing.JPanel();
        lbltitulo2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNoFac = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtCliCedula = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCliNombre = new javax.swing.JTextField();
        txtCliDireccion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCliTelefono = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnBuscarCliente = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        txtCliCorreo = new javax.swing.JTextField();
        txtCliId = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtProdCodigo = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtProdNombre = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtProdPrecio = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        btnBuscarProd = new javax.swing.JButton();
        spiCantidad = new javax.swing.JSpinner();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        btnProcesarPago = new javax.swing.JButton();
        txtTOTAL = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtIVA = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtSUBTOTAL = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnGenerarFactura = new javax.swing.JButton();

        DlgCliente.setSize(new java.awt.Dimension(545, 310));
        DlgCliente.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabladlg.setBackground(new java.awt.Color(255, 253, 227));
        tabladlg.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Cedula", "Nombre", "Apellido", "Telefono", "Correo", "Direccion"
            }
        ));
        jScrollPane3.setViewportView(tabladlg);
        if (tabladlg.getColumnModel().getColumnCount() > 0) {
            tabladlg.getColumnModel().getColumn(1).setHeaderValue("Cedula");
        }

        DlgCliente.getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 670, 200));

        jToolBar2.setBackground(new java.awt.Color(238, 227, 203));
        jToolBar2.setBorder(null);
        jToolBar2.setFloatable(false);
        jToolBar2.add(jSeparator4);

        jLabel17.setBackground(new java.awt.Color(238, 227, 203));
        jLabel17.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        jLabel17.setText("BUSCAR:  ");
        jToolBar2.add(jLabel17);

        txtbuscardlg.setBackground(new java.awt.Color(255, 253, 227));
        jToolBar2.add(txtbuscardlg);
        jToolBar2.add(jSeparator5);

        btnseleccionardlg.setBackground(new java.awt.Color(238, 227, 203));
        btnseleccionardlg.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        btnseleccionardlg.setText("SELECCIONAR");
        btnseleccionardlg.setBorder(null);
        btnseleccionardlg.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnseleccionardlg.setOpaque(true);
        jToolBar2.add(btnseleccionardlg);
        jToolBar2.add(jSeparator6);

        DlgCliente.getContentPane().add(jToolBar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 510, -1));

        jPanel5.setBackground(new java.awt.Color(238, 227, 203));

        lbltitulo1.setFont(new java.awt.Font("MS Gothic", 1, 24)); // NOI18N
        lbltitulo1.setText("SELECCIÓN DE CLIENTE");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(lbltitulo1)
                .addContainerGap(286, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lbltitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(291, Short.MAX_VALUE))
        );

        DlgCliente.getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 340));

        DlgProducto.setSize(new java.awt.Dimension(545, 310));
        DlgProducto.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabladlgProd.setBackground(new java.awt.Color(255, 253, 227));
        tabladlgProd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Descripcion", "Precio $", "Stock", "Fecha de caducidad"
            }
        ));
        jScrollPane4.setViewportView(tabladlgProd);

        DlgProducto.getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 670, 200));

        jToolBar3.setBackground(new java.awt.Color(238, 227, 203));
        jToolBar3.setBorder(null);
        jToolBar3.setFloatable(false);
        jToolBar3.add(jSeparator7);

        jLabel18.setBackground(new java.awt.Color(238, 227, 203));
        jLabel18.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        jLabel18.setText("BUSCAR:  ");
        jToolBar3.add(jLabel18);

        txtbuscardlg1.setBackground(new java.awt.Color(255, 253, 227));
        jToolBar3.add(txtbuscardlg1);
        jToolBar3.add(jSeparator8);

        btnseleccionardlgProd.setBackground(new java.awt.Color(238, 227, 203));
        btnseleccionardlgProd.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        btnseleccionardlgProd.setText("SELECCIONAR");
        btnseleccionardlgProd.setBorder(null);
        btnseleccionardlgProd.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnseleccionardlgProd.setOpaque(true);
        jToolBar3.add(btnseleccionardlgProd);
        jToolBar3.add(jSeparator9);

        DlgProducto.getContentPane().add(jToolBar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 690, -1));

        jPanel6.setBackground(new java.awt.Color(238, 227, 203));

        lbltitulo2.setFont(new java.awt.Font("MS Gothic", 1, 24)); // NOI18N
        lbltitulo2.setText("SELECCIÓN DE PRODUCTO");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(lbltitulo2)
                .addContainerGap(274, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lbltitulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(291, Short.MAX_VALUE))
        );

        DlgProducto.getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 340));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(130, 148, 96));
        jLabel1.setText("Farmacia ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, -1));

        jLabel2.setText("NO.");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 46, -1, 30));
        getContentPane().add(txtNoFac, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 54, -1));

        jPanel1.setBackground(new java.awt.Color(182, 227, 136));
        jPanel1.setForeground(new java.awt.Color(0, 204, 204));

        jLabel4.setText("Cedula");

        jLabel3.setText("Nombre");

        jLabel5.setText("Correo");

        jLabel6.setText("Direccion");

        jLabel7.setText("Telefono");

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel8.setText("DATOS DEL CLIENTE");

        btnBuscarCliente.setText("BUSCAR CLIENTE");
        btnBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClienteActionPerformed(evt);
            }
        });

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(159, 159, 159)
                        .addComponent(txtCliId, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCliCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCliNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCliDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                            .addComponent(txtCliCorreo))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(txtCliTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(43, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator2)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtCliId, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtCliTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscarCliente))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtCliCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtCliDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCliCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txtCliNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 1, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 84, 820, -1));

        jPanel2.setBackground(new java.awt.Color(182, 227, 136));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel12.setText("DATOS DEL PRODUCTO");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        jLabel13.setText("CODIGO PRODUCTO");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 46, -1, 30));
        jPanel2.add(txtProdCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 81, 22));
        txtProdCodigo.getAccessibleContext().setAccessibleName("");

        jLabel14.setText("NOMBRE");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, 20));
        jPanel2.add(txtProdNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 130, -1));

        jLabel15.setText("DESCRIPCION");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 50, -1, -1));
        jPanel2.add(txtProdPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, 112, -1));

        jLabel16.setText("CANTIDAD");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, -1, -1));

        btnBuscarProd.setText("BUSCAR PRODUCTO");
        jPanel2.add(btnBuscarProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        spiCantidad.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        jPanel2.add(spiCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, 110, -1));

        jLabel19.setText("PRECIO UNITARIO");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, -1, -1));

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        jScrollPane1.setViewportView(txtDescripcion);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 70, 160, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 225, 820, 170));

        jPanel3.setBackground(new java.awt.Color(225, 255, 177));

        btnProcesarPago.setText("Procesar Pago");

        jLabel11.setText("TOTAL");

        jLabel10.setText("IVA");

        jLabel9.setText("SUBTOTAL");

        btnGenerarFactura.setText("Generar Factura");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(509, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnGenerarFactura)
                                .addGap(156, 156, 156))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(169, 169, 169)
                                .addComponent(btnProcesarPago))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(289, 289, 289)
                        .addComponent(jLabel10)
                        .addGap(22, 22, 22)
                        .addComponent(txtIVA, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSUBTOTAL, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11)
                        .addGap(15, 15, 15)
                        .addComponent(txtTOTAL, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(57, 57, 57))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(425, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(txtSUBTOTAL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9))
                    .addComponent(txtTOTAL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtIVA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnProcesarPago)
                    .addComponent(btnGenerarFactura))
                .addGap(213, 213, 213))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClienteActionPerformed
     ModelCliente cli = new ModelCliente();
     cli.getClientes();
    }//GEN-LAST:event_btnBuscarClienteActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog DlgCliente;
    private javax.swing.JDialog DlgProducto;
    private javax.swing.JButton btnBuscarCliente;
    private javax.swing.JButton btnBuscarProd;
    private javax.swing.JButton btnGenerarFactura;
    private javax.swing.JButton btnProcesarPago;
    private javax.swing.JButton btnseleccionardlg;
    private javax.swing.JButton btnseleccionardlgProd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JToolBar.Separator jSeparator8;
    private javax.swing.JToolBar.Separator jSeparator9;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JToolBar jToolBar3;
    private javax.swing.JLabel lbltitulo1;
    private javax.swing.JLabel lbltitulo2;
    private javax.swing.JSpinner spiCantidad;
    private javax.swing.JTable tabladlg;
    private javax.swing.JTable tabladlgProd;
    private javax.swing.JTextField txtCliCedula;
    private javax.swing.JTextField txtCliCorreo;
    private javax.swing.JTextField txtCliDireccion;
    private javax.swing.JTextField txtCliId;
    private javax.swing.JTextField txtCliNombre;
    private javax.swing.JTextField txtCliTelefono;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtIVA;
    private javax.swing.JTextField txtNoFac;
    private javax.swing.JTextField txtProdCodigo;
    private javax.swing.JTextField txtProdNombre;
    private javax.swing.JTextField txtProdPrecio;
    private javax.swing.JTextField txtSUBTOTAL;
    private javax.swing.JTextField txtTOTAL;
    private javax.swing.JTextField txtbuscardlg;
    private javax.swing.JTextField txtbuscardlg1;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnBuscarCliente() {
        return btnBuscarCliente;
    }

    public void setBtnBuscarCliente(JButton btnBuscarCliente) {
        this.btnBuscarCliente = btnBuscarCliente;
    }

    public JButton getBtnseleccionardlg() {
        return btnseleccionardlg;
    }

    public void setBtnseleccionardlg(JButton btnseleccionardlg) {
        this.btnseleccionardlg = btnseleccionardlg;
    }

    public JTable getTabladlg() {
        return tabladlg;
    }

    public void setTabladlg(JTable tabladlg) {
        this.tabladlg = tabladlg;
    }

    public JTextField getTxtCliCedula() {
        return txtCliCedula;
    }

    public void setTxtCliCedula(JTextField txtCliCedula) {
        this.txtCliCedula = txtCliCedula;
    }

    public JTextField getTxtCliCorreo() {
        return txtCliCorreo;
    }

    public void setTxtCliCorreo(JTextField txtCliCorreo) {
        this.txtCliCorreo = txtCliCorreo;
    }

    public JTextField getTxtCliDireccion() {
        return txtCliDireccion;
    }

    public void setTxtCliDireccion(JTextField txtCliDireccion) {
        this.txtCliDireccion = txtCliDireccion;
    }

    public JTextField getTxtCliNombre() {
        return txtCliNombre;
    }

    public void setTxtCliNombre(JTextField txtCliNombre) {
        this.txtCliNombre = txtCliNombre;
    }

    public JTextField getTxtCliTelefono() {
        return txtCliTelefono;
    }

    public void setTxtCliTelefono(JTextField txtCliTelefono) {
        this.txtCliTelefono = txtCliTelefono;
    }

    public JTextField getTxtbuscardlg() {
        return txtbuscardlg;
    }

    public void setTxtbuscardlg(JTextField txtbuscardlg) {
        this.txtbuscardlg = txtbuscardlg;
    }

    public JDialog getDlgCliente() {
        return DlgCliente;
    }

    public void setDlgCliente(JDialog DlgCliente) {
        this.DlgCliente = DlgCliente;
    }

    public JTextField getTxtCliId() {
        return txtCliId;
    }

    public void setTxtCliId(JTextField txtCliId) {
        this.txtCliId = txtCliId;
    }

    public JDialog getDlgProducto() {
        return DlgProducto;
    }

    public void setDlgProducto(JDialog DlgProducto) {
        this.DlgProducto = DlgProducto;
    }

    public JButton getBtnseleccionardlgProd() {
        return btnseleccionardlgProd;
    }

    public void setBtnseleccionardlgProd(JButton btnseleccionardlgProd) {
        this.btnseleccionardlgProd = btnseleccionardlgProd;
    }

    public JTable getTabladlgProd() {
        return tabladlgProd;
    }

    public void setTabladlgProd(JTable tabladlgProd) {
        this.tabladlgProd = tabladlgProd;
    }

    public JTextField getTxtbuscardlg1() {
        return txtbuscardlg1;
    }

    public void setTxtbuscardlg1(JTextField txtbuscardlg1) {
        this.txtbuscardlg1 = txtbuscardlg1;
    }

    public JButton getBtnBuscarProd() {
        return btnBuscarProd;
    }

    public void setBtnBuscarProd(JButton btnBuscarProd) {
        this.btnBuscarProd = btnBuscarProd;
    }

    public JTextField getTxtProdCodigo() {
        return txtProdCodigo;
    }

    public void setTxtProdCodigo(JTextField txtProdCodigo) {
        this.txtProdCodigo = txtProdCodigo;
    }

    public JTextField getTxtProdNombre() {
        return txtProdNombre;
    }

    public void setTxtProdNombre(JTextField txtProdNombre) {
        this.txtProdNombre = txtProdNombre;
    }

    public JTextField getTxtProdPrecio() {
        return txtProdPrecio;
    }

    public void setTxtProdPrecio(JTextField txtProdPrecio) {
        this.txtProdPrecio = txtProdPrecio;
    }

    public JTextField getTxtNoFac() {
        return txtNoFac;
    }

    public void setTxtNoFac(JTextField txtNoFac) {
        this.txtNoFac = txtNoFac;
    }

    public JSpinner getSpiCantidad() {
        return spiCantidad;
    }

    public void setSpiCantidad(JSpinner spiCantidad) {
        this.spiCantidad = spiCantidad;
    }

    public JButton getBtnGenerarFactura() {
        return btnGenerarFactura;
    }

    public void setBtnGenerarFactura(JButton btnGenerarFactura) {
        this.btnGenerarFactura = btnGenerarFactura;
    }

    public JButton getBtnProcesarPago() {
        return btnProcesarPago;
    }

    public void setBtnProcesarPago(JButton btnProcesarPago) {
        this.btnProcesarPago = btnProcesarPago;
    }

    public JTextField getTxtIVA() {
        return txtIVA;
    }

    public void setTxtIVA(JTextField txtIVA) {
        this.txtIVA = txtIVA;
    }

    public JTextField getTxtSUBTOTAL() {
        return txtSUBTOTAL;
    }

    public void setTxtSUBTOTAL(JTextField txtSUBTOTAL) {
        this.txtSUBTOTAL = txtSUBTOTAL;
    }

    public JTextField getTxtTOTAL() {
        return txtTOTAL;
    }

    public void setTxtTOTAL(JTextField txtTOTAL) {
        this.txtTOTAL = txtTOTAL;
    }

    public JTextArea getTxtDescripcion() {
        return txtDescripcion;
    }

    public void setTxtDescripcion(JTextArea txtDescripcion) {
        this.txtDescripcion = txtDescripcion;
    }

 
}
